name: actions

on:
  push:
    branches:
        - main

jobs:
  job1:
    name: train-dev-data
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job_dev.yml --resource-group rg-dp100-MLOps --workspace-name mlw-dp100-MLOps

    - name: Echo
      run: echo "train-dev-data ran successfully"
        
  job2:
    name: train-prod-data
    runs-on: ubuntu-latest
    environment: prod
    needs: job1
    if: ${{ success() }}

    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job_prod.yml --resource-group rg-dp100-MLOps --workspace-name mlw-dp100-MLOps --stream

    - name: Echo
      run: echo "train-prod-data ran successfully"
