name: Deploy latest version of model

on:
  workflow_dispatch:

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repo
      uses: actions/checkout@main
      
    - name: Install az ml extension
      run: az extension add -n ml -y
      
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Create endpoint
      run: |
        endpoint_name=diabetes-endpoint
        az ml online-endpoint create --name $endpoint_name --model diabetes-prod-log-regression:1 --compute aml-compute --resource-group rg-dp100-MLOps --workspace-name mlw-dp100-MLOps --auto-update true

    - name: Deploy model to endpoint
      run: |
        az ml online-endpoint update -n $endpoint_name --query endpoint.status -o tsv
