name: Pull Request Merged

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Echo message
      run: echo "Will add code checks here in next challenge"
